language: objective-c

xcode_workspace: JCSegueUserInfo.xcworkspace
xcode_scheme: JCSegueUserInfo

before_install: 
    - brew unlink xctool
    - brew install xctool --HEAD
    - export LC_ALL="en_US.UTF-8"
    - gem install cocoapods

script: xctool -workspace JCSegueUserInfo.xcworkspace -scheme JCSegueUserInfo test -sdk iphonesimulator
